# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-06 09:33
from __future__ import unicode_literals

import SWtest.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=300, verbose_name='Answer')),
                ('true_or_false', models.BooleanField(choices=[(True, 'Right'), (False, 'False')], default=False, max_length=5, verbose_name='Right Answer?')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj', models.TextField(max_length=300, verbose_name='Question')),
                ('img_pic', models.ImageField(blank=True, help_text='Not required', upload_to=SWtest.models.path, verbose_name='Image for question')),
                ('answer1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question1', to='SWtest.Answ', verbose_name='Answer')),
                ('answer2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question2', to='SWtest.Answ', verbose_name='Answer')),
                ('answer3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question3', to='SWtest.Answ', verbose_name='Answer')),
                ('answer4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question4', to='SWtest.Answ', verbose_name='Answer')),
            ],
        ),
    ]
